# Generated by Django 5.1.3 on 2024-11-14 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_galeria_zapatillas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
